# Generated by Django 3.2.9 on 2021-12-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_table_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
