# Generated by Django 3.2 on 2021-12-15 23:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_date']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date_time_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date_time_start',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[(0, '11:00'), (1, '11:30'), (2, '12:00'), (3, '12:30'), (4, '13:00'), (5, '13:30'), (6, '14:00'), (7, '14:30'), (8, '15:00'), (9, '15:30'), (10, '16:00'), (11, '16:30'), (12, '17:00'), (13, '17:30'), (14, '18:00'), (15, '18:30'), (16, '19:00'), (17, '19:30'), (18, '20:00'), (19, '20:30'), (20, '21:00'), (21, '21:30')], default=(21, '21:30'), max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='party_size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='table',
            name='size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
