# Generated by Django 3.2 on 2021-12-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20211220_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_date_start']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='booking_date_start',
        ),
    ]
