# Generated by Django 3.2 on 2021-12-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20211220_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date_start',
            field=models.DateTimeField(default='12/20/2021 20:37', help_text='mm/dd/yyyy 14:30'),
        ),
    ]
