# Generated by Django 3.2 on 2021-12-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_table_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='your_email@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='party_size',
            field=models.IntegerField(default=2),
        ),
    ]
